version: '2'
services:
  ipfs-cluster:
    image: evannetwork/ipfs-cluster:v0.10.0
    container_name: ipfs_cluster
    restart: always
    environment:
      - IPFS_API=\/ip4\/172.16.0.2\/tcp\/5001
      - IPFS_CLUSTER_SECRET=SECRET
    command: daemon --upgrade --bootstrap PEER
    volumes:
      - ./ipfs-cluster-data:/data/ipfs-cluster
    ports:
      - "9096:9096"
    networks:
      ipfs_cluster_net:
        ipv4_address: 172.16.0.3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
  ipfs-node:
    image:  evannetwork/go-ipfs:v0.4.19
    container_name: ipfs_node
    restart: always
    environment:
      - IPFS_STORAGE_MAX=10GB
      - IPFS_ORIGIN_ALLOW=[]
      - IPFS_BOOTSTRAP_PEERS=
    expose:
      - "5001"
    ports:
      - "4001:4001"
    volumes:
      - ipfs-data:/data/ipfs
      - ./swarm-key/swarm.key:/data/ipfs/swarm.key
      - ipfs-staging:/export
    networks:
      ipfs_cluster_net:
        ipv4_address: 172.16.0.2
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  nginx-ipfs:
    image: evannetwork/nginx-ipfs
    container_name: nginx_ipfs
    restart: always
    command: /bin/sh -c "envsubst '$$SSL_DOMAIN $$IPFS_SERVER_NAME $$CHAIN_ENDPOINT $$PAYMENTS_ENDPOINT' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;' -c '/etc/nginx/nginx.conf'"
    environment:
      - SSL_DOMAIN=ipfs.evan.network
      - IPFS_SERVER_NAME=ipfs.evan.network
      - PAYMENTS_ENDPOINT=https://payments.test.evan.network
      - CHAIN_ENDPOINT=https://testcore.evan.network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-config/ssl:/ssl
    networks:
      ipfs_cluster_net:
        ipv4_address: 172.16.0.4
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  blacklist-redis:
    image: evannetwork/blacklist-redis:latest
    container_name: blacklist-redis
    restart: always
    tmpfs:
      - /data
    expose:
      - "6379"
    networks:
      ipfs_cluster_net:
        ipv4_address: 172.16.0.5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

volumes:
  ipfs-data:
  ipfs-staging:
  ipfs-cluster-data:

networks:
  ipfs_cluster_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.0.1/24
        gateway: 172.16.0.1
